/***************************************************************************************************
 * Copyright (c) 2022, Qualcomm Innovation Center, Inc. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 * and associated documentation files (the “Software”), to deal in the Software without
 * restriction, including without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or
 * substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 * BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 * DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 **************************************************************************************************/
 /***************************************************************************************************
 * tpsc_connector_api.h
 *
 * This is the C language header file for a Secure Component connector.
 *
 **************************************************************************************************/
 

#ifndef tpsc_connector_api_h
#define tpsc_connector_api_h

#pragma once

/* Generated with cbindgen:0.21.0 */

/*****                            AUTOGENERATED FILE - DO NOT EDIT                            *****/


#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "tpsc_client_api.h"

/**
 * The Connector structure is exposed by every instance of a connector, and defines the function  * calls between the TPS Client API and the connector implementation.
 */
typedef struct {
    uint32_t (*connect)(uint32_t connection_method, const TPSC_ConnectionData *connection_data, uint32_t *connection_id);
    uint32_t (*disconnect)(uint32_t connection_id);
    uint32_t (*service_discovery)(TPSC_ServiceIdentifier *result_buf, size_t *len);
    uint32_t (*open_session)(const TPSC_UUID *service_instance, uint32_t *session_id);
    uint32_t (*close_session)(uint32_t session_id);
    uint32_t (*execute_transaction)(const uint8_t *send_buf, size_t send_len, uint8_t *recv_buf, size_t recv_len, uint32_t *transaction_id);
    uint32_t (*cancel_transaction)(uint32_t transaction_id);
} TPSC_Connector;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern const TPSC_Connector *TPSC_GetConnectorAPI(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* tpsc_connector_api_h */
